//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDGI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtoPreguntas
    {
        public int Id_Pilar { get; set; }
        public int Id_Bloque { get; set; }
        public int Id_Factor { get; set; }
        public int Id_Elemento { get; set; }
        public int Id_Pregunta { get; set; }
        public string Nom_Pilar { get; set; }
        public string Nom_Bloque { get; set; }
        public string Nom_Factor { get; set; }
        public string Nom_Elemento { get; set; }
        public string Nom_Pregunta { get; set; }
    }
}
