//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDGI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Bloque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Bloque()
        {
            this.Tbl_Factor = new HashSet<Tbl_Factor>();
        }
    
        public int Id_Bloque { get; set; }
        public string Nom_Bloque { get; set; }
        public bool EstaActivo { get; set; }
        public int Id_Pilar { get; set; }
    
        public virtual Tbl_Pilar Tbl_Pilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Factor> Tbl_Factor { get; set; }
    }
}
