//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDGI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gestor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gestor()
        {
            this.Tbl_EmpresaGestor = new HashSet<Tbl_EmpresaGestor>();
            this.Tbl_Respuesta = new HashSet<Tbl_Respuesta>();
        }
    
        public int Id_Gestor { get; set; }
        public string Nom_Gestor { get; set; }
        public string Ape_Gestor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EmpresaGestor> Tbl_EmpresaGestor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Respuesta> Tbl_Respuesta { get; set; }
    }
}
