//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solucion_IDGI.Empresas {
    
    
    public partial class frmCrudEmpresa {
        
        /// <summary>
        /// UC_CrudEmpresa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Solucion_IDGI.Empresas.UC_CrudEmpresa UC_CrudEmpresa;
    }
}
