//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDGI.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Pais()
        {
            this.Tbl_Departamento = new HashSet<Tbl_Departamento>();
        }
    
        public int Id_Pais { get; set; }
        public string Nom_Pais { get; set; }
        public string Codigo_Pais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Departamento> Tbl_Departamento { get; set; }
    }
}
