//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDGI.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Pais
    {
        public int Id_Pais { get; set; }
        public string Nom_Pais { get; set; }
    }
}
